name: User Service CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag to deploy"
        required: false
        default: ""
        type: string

permissions:
  contents: read
  packages: write

jobs:

  cicd:

    uses: abj-developer/deployment-config/.github/workflows/reusable-service-cicd.yaml@main

    with:
      service_name: user-service
      deploy_env: dev
      mysql_database: userdb_test
      image_tag: ${{ inputs.image_tag }}

    secrets:
      AWS_HOST: ${{ secrets.AWS_HOST }}
      AWS_USERNAME: ${{ secrets.AWS_USERNAME }}
      AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}